name: Validate PR Running

on:
  pull_request:
    branches:
      - '**'
    types: [ labeled ]
  workflow_dispatch:
    branches:
      - '**'

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up GCC-11
      uses: egor-tensin/setup-gcc@v2
      with:
        version: 11
        platform: x64

    - name: Set up QEMU
      run: |
        sudo apt update
        sudo apt install -y qemu-system-x86 qemu-utils

    - name: Run in Qemu
      run: make CC=gcc-11 qemu
